apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-etl-deployment
  namespace: stock-etl-namespace
  labels:
    app: stock-etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-etl
  template:
    metadata:
      labels:
        app: stock-etl
    spec:
      containers:
      - name: stock-etl-container
        image: stock-etl-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        env:
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017/"
          - name: MINIO_HOST
            value: "minio-service.minio-dev.svc.cluster.local"
          - name: MINIO_PORT
            value: "6544"
          - name: MINIO_ACCESS_KEY
            value: "minio"
          - name: MINIO_SECRET_KEY
            value: "minio123"
          - name: SPARK_MASTER_URL
            value: "spark://spark-master-svc.spark-namespace.svc.cluster.local:7077"
          - name: SPARK_DRIVER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPARK_DRIVER_MEMORY
            value: "1g"
          - name: SPARK_EXECUTOR_MEMORY
            value: "8g"
          - name: SPARK_TOTAL_EXECUTOR_CORES
            value: "3"
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"