version: "3.8"

services:
  spark-master:
    container_name: spark-master
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./entrypoint.sh", "master"]
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"       # Spark master port for job submission
      - "8080:8080"       # Spark master UI port
    volumes:
      - spark-logs:/opt/spark/spark-events

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./entrypoint.sh", "worker"]
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark-logs:/opt/spark/spark-events

  spark-history:
    container_name: spark-history
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./entrypoint.sh", "history"]
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "18080:18080"     # Spark History Server port
    volumes:
      - spark-logs:/opt/spark/spark-events

  app:
    container_name: stock-etl-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - spark-master
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8000:8000"

  mongo:
    image: mongo:6.0
    container_name: stock-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  spark-logs:
  mongo-data:
