# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: minio-manual
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-0
  labels:
    app: minio-app
spec:
  storageClassName: minio-manual
  claimRef:
    name: data-datasaku-minio-0
    namespace: minio-dev
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/minio/minio0
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-1
  labels:
    app: minio-app
spec:
  storageClassName: minio-manual
  claimRef:
    name: data-datasaku-minio-1
    namespace: minio-dev
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/minio/minio1