# why we name the metadata like below, https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-datasaku-minio-0
  labels:
    app: minio-app
spec:
  storageClassName: minio-manual
  volumeName: minio-volume-0
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-datasaku-minio-1
  labels:
    app: minio-app
spec:
  storageClassName: minio-manual
  volumeName: minio-volume-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi