apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-spark-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: airflow-sa
  namespace: airflow
roleRef:
  kind: ClusterRole
  name: airflow-spark-clusterrole
  apiGroup: rbac.authorization.k8s.io
