apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-stock-etl
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: "stock-etl-app:latest"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///etl/etl_main.py"
  arguments:
    - "stocks_historical_to_2025_02_04"
  sparkVersion: "3.5.5"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "2g"
    serviceAccount: spark
    env:
      - name: MONGO_URI
        value: "mongodb://mongo-service.stock-mongo-namespace.svc.cluster.local:27017/"
      - name: MINIO_HOST
        value: "minio-service.minio-dev.svc.cluster.local"
      - name: MINIO_PORT
        value: "6544"
      - name: MINIO_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: minio-access-key
      - name: MINIO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: minio-secret-key
  executor:
    cores: 2
    instances: 1
    memory: "4g"
    env:
      - name: MONGO_URI
        value: "mongodb://mongo-service.stock-mongo-namespace.svc.cluster.local:27017/"
      - name: MINIO_HOST
        value: "minio-service.minio-dev.svc.cluster.local"
      - name: MINIO_PORT
        value: "6544"
      - name: MINIO_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: minio-access-key
      - name: MINIO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-secret
            key: minio-secret-key