apiVersion: v1
kind: Service
metadata:
  name: stock-etl-service
  namespace: stock-etl-namespace
  labels:
    app: stock-etl
spec:
  type: NodePort
  selector:
    app: stock-etl
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
