apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api-deployment
  namespace: stock-api-namespace
  labels:
    app: stock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
      - name: stock-api-container
        image: stock-api-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: spark-logs-volume
            mountPath: /tmp/spark-events
        env:
          - name: MONGO_URI
            value: "mongodb://mongo-service.stock-mongo-namespace.svc.cluster.local:27017/"
          - name: MINIO_HOST
            value: "minio-service.minio-dev.svc.cluster.local"
          - name: MINIO_PORT
            value: "6544"
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minio-access-key
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minio-secret-key
          - name: SPARK_MASTER_URL
            value: "spark://spark-master-svc.spark-namespace.svc.cluster.local:7077"
          - name: SPARK_DRIVER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPARK_DRIVER_MEMORY
            value: "1g"
          - name: SPARK_EXECUTOR_MEMORY
            value: "8g"
          - name: SPARK_TOTAL_EXECUTOR_CORES
            value: "3"
          - name: SPARK_MAX_EXECUTOR_CORES
            value: "4"
          - name: SPARK_EVENTLOG_DIR
            value: "file:///tmp/spark-events"
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
      volumes:
      - name: spark-logs-volume
        persistentVolumeClaim:
          claimName: spark-logs-pvc