apiVersion: v1
kind: Service
metadata:
  name: stock-api-service
  namespace: stock-api-namespace
  labels:
    app: stock-api
spec:
  type: NodePort
  selector:
    app: stock-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
