apiVersion: v1
kind: Service
metadata:
  name: spark-history-service
  namespace: stock-etl-namespace
spec:
  type: NodePort
  ports:
    - name: http
      port: 18080
      targetPort: 18080
      nodePort: 31880
  selector:
    app: spark-history-server